# Generated by Django 3.2.7 on 2021-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
